
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 31 18:24:33 CST 2019
//----------------------------------------------------

package lexCode;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Return = 96;
  public static final int Parentesis_c = 32;
  public static final int Parentesis_a = 31;
  public static final int Into = 54;
  public static final int Full = 76;
  public static final int Coma = 15;
  public static final int Corchete_c = 64;
  public static final int MenorQue = 82;
  public static final int Corchete_a = 63;
  public static final int Punto = 9;
  public static final int Count = 65;
  public static final int Output = 92;
  public static final int Unique = 41;
  public static final int For = 100;
  public static final int Procedure = 90;
  public static final int Add = 12;
  public static final int Max = 67;
  public static final int Cursor = 98;
  public static final int Int = 5;
  public static final int Asterisco = 59;
  public static final int Returns = 95;
  public static final int Avg = 66;
  public static final int Values = 55;
  public static final int Null = 39;
  public static final int Create = 88;
  public static final int Bit = 7;
  public static final int Tran = 50;
  public static final int Having = 80;
  public static final int Punto_Coma = 16;
  public static final int FLOAT = 43;
  public static final int Update = 103;
  public static final int MenorIgual = 84;
  public static final int Rebuild = 29;
  public static final int Insert = 53;
  public static final int String = 8;
  public static final int Begin = 45;
  public static final int Negar = 17;
  public static final int Commit = 47;
  public static final int Foreign = 36;
  public static final int Transaction = 51;
  public static final int Collate = 28;
  public static final int Primary = 13;
  public static final int Desc = 35;
  public static final int Save = 48;
  public static final int Only = 102;
  public static final int Function = 94;
  public static final int End = 46;
  public static final int MayorQue = 81;
  public static final int Column = 27;
  public static final int Group = 78;
  public static final int Outer = 73;
  public static final int Right = 75;
  public static final int Table = 23;
  public static final int Or = 86;
  public static final int And = 85;
  public static final int espacio = 14;
  public static final int Drop = 18;
  public static final int Database = 19;
  public static final int On = 24;
  public static final int Truncate = 2;
  public static final int INT = 42;
  public static final int If = 10;
  public static final int Key = 37;
  public static final int User = 22;
  public static final int Id = 4;
  public static final int MayorIgual = 83;
  public static final int BIT = 44;
  public static final int EOF = 0;
  public static final int Of = 25;
  public static final int Distinct = 62;
  public static final int By = 79;
  public static final int Left = 74;
  public static final int Scroll = 99;
  public static final int From = 70;
  public static final int Inner = 72;
  public static final int Constraint = 30;
  public static final int Read = 101;
  public static final int Declare = 97;
  public static final int Nonclustered = 33;
  public static final int error = 1;
  public static final int Top = 57;
  public static final int Asc = 34;
  public static final int Float = 6;
  public static final int Arroba = 52;
  public static final int References = 38;
  public static final int Join = 71;
  public static final int Sum = 69;
  public static final int As = 60;
  public static final int VARCHAR = 93;
  public static final int Select = 56;
  public static final int All = 61;
  public static final int Rollback = 49;
  public static final int Go = 3;
  public static final int Out = 91;
  public static final int Not = 40;
  public static final int Exists = 11;
  public static final int View = 21;
  public static final int Alter = 26;
  public static final int Percent = 58;
  public static final int Igual = 77;
  public static final int Index = 20;
  public static final int Order = 87;
  public static final int Min = 68;
  public static final int Proc = 89;
}

