
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 31 12:46:14 CST 2019
//----------------------------------------------------

package lexCode;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 32;
  public static final int Parentesis_a = 31;
  public static final int Into = 56;
  public static final int Full = 78;
  public static final int Coma = 15;
  public static final int Corchete_c = 66;
  public static final int MenorQue = 84;
  public static final int Corchete_a = 65;
  public static final int Punto = 9;
  public static final int Count = 67;
  public static final int Unique = 41;
  public static final int Add = 12;
  public static final int Max = 69;
  public static final int Int = 5;
  public static final int Asterisco = 61;
  public static final int Avg = 68;
  public static final int Values = 57;
  public static final int Null = 39;
  public static final int Bit = 7;
  public static final int Tran = 52;
  public static final int NVARCHAR = 46;
  public static final int Having = 82;
  public static final int Punto_Coma = 16;
  public static final int FLOAT = 43;
  public static final int MenorIgual = 86;
  public static final int Rebuild = 29;
  public static final int Insert = 55;
  public static final int String = 8;
  public static final int Begin = 47;
  public static final int Negar = 17;
  public static final int Commit = 49;
  public static final int Foreign = 36;
  public static final int Transaction = 53;
  public static final int Collate = 28;
  public static final int Primary = 13;
  public static final int Desc = 35;
  public static final int Save = 50;
  public static final int End = 48;
  public static final int MayorQue = 83;
  public static final int Column = 27;
  public static final int Group = 80;
  public static final int Outer = 75;
  public static final int Right = 77;
  public static final int Table = 23;
  public static final int Or = 88;
  public static final int And = 87;
  public static final int espacio = 14;
  public static final int Drop = 18;
  public static final int Database = 19;
  public static final int On = 24;
  public static final int Truncate = 2;
  public static final int INT = 42;
  public static final int If = 10;
  public static final int Key = 37;
  public static final int User = 22;
  public static final int Id = 4;
  public static final int MayorIgual = 85;
  public static final int BIT = 44;
  public static final int EOF = 0;
  public static final int Of = 25;
  public static final int Distinct = 64;
  public static final int By = 81;
  public static final int Left = 76;
  public static final int From = 72;
  public static final int Inner = 74;
  public static final int Constraint = 30;
  public static final int Nonclustered = 33;
  public static final int error = 1;
  public static final int Top = 59;
  public static final int Asc = 34;
  public static final int Float = 6;
  public static final int Arroba = 54;
  public static final int References = 38;
  public static final int Join = 73;
  public static final int Sum = 71;
  public static final int As = 62;
  public static final int VARCHAR = 45;
  public static final int Select = 58;
  public static final int All = 63;
  public static final int Rollback = 51;
  public static final int Go = 3;
  public static final int Not = 40;
  public static final int Exists = 11;
  public static final int View = 21;
  public static final int Alter = 26;
  public static final int Percent = 60;
  public static final int Igual = 79;
  public static final int Index = 20;
  public static final int Order = 89;
  public static final int Min = 70;
}

